In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!cp -r '/content/drive/My Drive/fish_data_small.zip' fish_data_small.zip

In [ ]:
!unzip /content/fish_data_small.zip

In [4]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import models
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import optimizers
import cv2
import numpy as np
import glob
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras import backend as K

In [5]:
# // train_data path
train_path = "/content/fish_data_small/train/"
#// test_data path
test_path="/content/fish_data_small/test/"

In [6]:
labels=[]
label_paths = glob.glob(train_path+"*")
for t_path in label_paths:
    labels.append(t_path[len(train_path):])
labels.sort()

#라벨들을 프린트 하시오
#code here
print(labels)

['10_Kanari', '1_Ko_dung_uh', '2_Thom_bang_yi', '3_Bang_uh_dom', '4_Bum-dom', '5_Yong-chi', '6_Cham_dom', '7_Jul_jun', '8_Gam_sung_dom', '9_Nong_uh']


In [7]:
picture_size = 150
train_data = []
train_data_label =[]

for label in labels:
    print (label)
    img_files = glob.glob(train_path+label+"/*.*")
    num_label = labels.index(label)
    print("data size for " + label + " : " + str(len(img_files)))
    for img_file in img_files:
        #print("loading "+img_file)
        img = cv2.imread(img_file)
        img = cv2.resize(img,(picture_size,picture_size))
        train_data.append(img)
        train_data_label.append(num_label)

10_Kanari
data size for 10_Kanari : 200
1_Ko_dung_uh
data size for 1_Ko_dung_uh : 200
2_Thom_bang_yi
data size for 2_Thom_bang_yi : 200
3_Bang_uh_dom
data size for 3_Bang_uh_dom : 200
4_Bum-dom
data size for 4_Bum-dom : 200
5_Yong-chi
data size for 5_Yong-chi : 200
6_Cham_dom
data size for 6_Cham_dom : 200
7_Jul_jun
data size for 7_Jul_jun : 200
8_Gam_sung_dom
data size for 8_Gam_sung_dom : 200
9_Nong_uh
data size for 9_Nong_uh : 200


In [8]:
picture_size = 150
test_data = []
test_data_label =[]

#test_data와 test_data_label에 적절한 데이터를 채우시오 (train_data 참고)
#code here

for label in labels:
    print (label)
    img_files = glob.glob(train_path+label+"/*.*")
    num_label = labels.index(label)
    print("data size for " + label + " : " + str(len(img_files)))
    for img_file in img_files:
        #print("loading "+img_file)
        img = cv2.imread(img_file)
        img = cv2.resize(img,(picture_size,picture_size))
        test_data.append(img)
        test_data_label.append(num_label)

10_Kanari
data size for 10_Kanari : 200
1_Ko_dung_uh
data size for 1_Ko_dung_uh : 200
2_Thom_bang_yi
data size for 2_Thom_bang_yi : 200
3_Bang_uh_dom
data size for 3_Bang_uh_dom : 200
4_Bum-dom
data size for 4_Bum-dom : 200
5_Yong-chi
data size for 5_Yong-chi : 200
6_Cham_dom
data size for 6_Cham_dom : 200
7_Jul_jun
data size for 7_Jul_jun : 200
8_Gam_sung_dom
data size for 8_Gam_sung_dom : 200
9_Nong_uh
data size for 9_Nong_uh : 200


In [17]:
X_train = np.array(train_data)
y_train = np.array(train_data_label)

X_train = X_train/255
y_train = y_train/255

#아래서 모델 생성할때 Normalization사용안해도됨

# #train_test_split를 이용하여 훈련데이터셋과 검증데이터셋으로 나누기. 검증데이터셋 20%, 인자로 random_state = 230 지정
# X_train, X_val, y_train, y_val = train_test_split(x, y, test_size = 0.2, random_state=230)

Y_train = to_categorical(y_train, len(labels))
# Y_val = to_categorical(y_val, len(labels))

#test_data[]와 test_data_lable[]을 이용하여 테스트셋 생성
X_test = np.array(test_data)    # code here:  test_data 이용
y_test = np.array(test_data_label)    # code here: test_data_label 이용
Y_test = to_categorical(y_test, len(labels))     # code here: y_test를 one_hot vector로 변환

X_test = X_test/255  

In [18]:
!pip install autokeras

In [19]:
import autokeras as ak

In [20]:
tf.keras.backend.clear_session()

In [21]:
input_node = ak.ImageInput()
output_node = ak.Normalization()(input_node)
output_node1 = ak.ConvBlock()(output_node)
output_node2 = ak.ConvBlock()(output_node)
output_node = ak.Merge()([output_node1, output_node2])
output_node = ak.ClassificationHead()(output_node)

In [22]:
model = ak.AutoModel(
    inputs = input_node, outputs=output_node, overwrite=True, max_trials=3
)
model.fit(X_train, Y_train, epochs=30)

Trial 3 Complete [00h 02m 08s]
val_loss: 0.0

Best val_loss So Far: 0.0
Total elapsed time: 00h 05m 16s
INFO:tensorflow:Oracle triggered exit
Epoch 1/30
63/63 [==============================] - 7s 90ms/step - loss: 0.0398 - accuracy: 0.9845
Epoch 2/30
63/63 [==============================] - 6s 89ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 3/30
63/63 [==============================] - 6s 91ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 4/30
63/63 [==============================] - 6s 91ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 5/30
63/63 [==============================] - 6s 90ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 6/30
63/63 [==============================] - 6s 89ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 7/30
63/63 [==============================] - 6s 90ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 8/30
63/63 [==============================] - 6s 90ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 9/30
63/63 [====================

In [23]:
predicted_y = model.predict(X_test)
print(predicted_y)
print(model.evaluate(X_test, Y_test))

63/63 [==============================] - 4s 39ms/step
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
63/63 [==============================] - 4s 38ms/step - loss: 78.6458 - accuracy: 0.1000
[78.64579010009766, 0.10000000149011612]
