In [1]:
import cv2

image = cv2.imread("images/flip_test.jpg", cv2.IMREAD_COLOR)

if image is None:
    raise Exception("영상파일읽기 오류발생")
    
x_axis = cv2.flip(image, 0) #0 -> x축 기준 상하 뒤집기
y_axis = cv2.flip(image, 1) #1 -> y축 기준 좌우뒤집기
xy_axis = cv2.flip(image, -1) #-1 -> x,y,축 기준 모두 뒤집기
rep_image12 = cv2.repeat(image, 1,2) # 1 x 2 반복 복사
rep_image21 = cv2.repeat(image, 2,1) # 2 x 1 반복 복사

trans_image = cv2.transpose(image) # 행렬 전치

titles = ['image', 'x_axis', 'y_axis', 'xy_axis', 'rep_image12','rep_image21', 'trans_image']

for title in titles:
    cv2.imshow(title, eval(title))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
import numpy as np

ch0 = np.zeros((2,4), np.uint8) + 10
ch1 = np.zeros((2,4), np.uint8) * 10
ch2 = np.ones((2,4), np.uint8) + 20
ch3 = np.ones((2,4), np.uint8) *20

ch4 = np.zeros((2,4), np.uint8)
ch4[:] = 30
ch4[0,1] = 1

ch5 = np.ones((2,4), np.uint8)
ch5[:] = 30
ch5[1:2] = 10

print('ch0', '\n', ch0, '\n')
print('ch1', '\n', ch1, '\n')
print('ch2', '\n', ch2, '\n')
print('ch3', '\n', ch3, '\n')
print('ch4', '\n', ch4, '\n')
print('ch5', '\n', ch5, '\n')


ch0 
 [[10 10 10 10]
 [10 10 10 10]] 

ch1 
 [[0 0 0 0]
 [0 0 0 0]] 

ch2 
 [[21 21 21 21]
 [21 21 21 21]] 

ch3 
 [[20 20 20 20]
 [20 20 20 20]] 

ch4 
 [[30  1 30 30]
 [30 30 30 30]] 

ch5 
 [[30 30 30 30]
 [10 10 10 10]] 



In [2]:
import cv2

image = cv2.imread('images/logo.jpg', cv2.IMREAD_COLOR)
if image is None:
    raise Exception("영상 파일 읽기 오류 발생")
if image.ndim != 3:
    raise Exception("컬러 영상 아님")

bgr = cv2.split(image)
print("bgr channel:", len(bgr))

cv2.imshow("image", image)
cv2.imshow("Blue channel", bgr[0])
cv2.imshow("Green channel", bgr[1])
cv2.imshow("Red channel", bgr[2])

cv2.waitKey()
cv2.destroyAllWindows()


bgr channel: 3


In [3]:
import numpy as np
import cv2

image = cv2.imread('images/logo.jpg', cv2.IMREAD_COLOR)
if image is None:
    raise Exception("영상 파일 읽기 오류 발생")
if image.ndim != 3:
    raise Exception("컬러 영상 아님")

b,g,r = cv2.split(image)
print(image.shape)

zeros = np.zeros((image.shape[:2]), dtype="uint8")

b = cv2.merge([b, zeros, zeros])
g = cv2.merge([zeros, g, zeros])
r = cv2.merge([zeros, zeros, r])
# bgr = cv2.merge([b,g,r]) #오류뜨는데 다른 방법이 있다고 함 ㅠㅠ

cv2.imshow("image", image)
cv2.imshow("Blue channel", b)
cv2.imshow("Green channel", g)
cv2.imshow("Red channel", r)
# cv2.imshow("BGR", bgr) #오류뜨는데 다른 방법이 있다고 함 ㅠㅠ

cv2.waitKey()
cv2.destroyAllWindows()


(308, 250, 3)


In [1]:
import numpy as np
import cv2
m1 = np.full((3,6), 10, np.uint8)
m2 = np.full((3,6), 10, np.uint8)
m_mask = np.zeros(m1.shape, np.uint8) #(3,6)
m_mask[:,3:] = 1 # m_mask[행,열]

m_add1 = cv2.add(m1, m2) # m1+m2
m_add2 = cv2.add(m1, m2, 
                 mask=m_mask) # 관심영역덧셈
m_div1 = cv2.divide(m1,m2)
m1 = m1.astype(np.float32)
m2 = np.float32(m2)
m_div2 = cv2.divide(m1,m2)

titles = ['m1', 'm2', 'm_mask', 'm_add1', 'm_add2', 'm_div1', 'm_div2']
print('m1',' \n', m1)
print()
print('m2',' \n', m2)
print()
print(' m_mask', '\n', m_mask)
print()
print('m_add1',' \n', m_add1)
print()
print('m_add2',' \n', m_add2)
print()
print('m_div1',' \n', m_div1)
print()
print('m_div2',' \n', m_div2)

m1  
 [[10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]]

m2  
 [[10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]]

 m_mask 
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]

m_add1  
 [[20 20 20 20 20 20]
 [20 20 20 20 20 20]
 [20 20 20 20 20 20]]

m_add2  
 [[ 0  0  0 20 20 20]
 [ 0  0  0 20 20 20]
 [ 0  0  0 20 20 20]]

m_div1  
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

m_div2  
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [2]:
v1 = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]],np.float32)

v1_pow2 = cv2.pow(v1,2)

v1_pow3 = cv2.pow(v1,3)

v1_pow4 = cv2.pow(v1,4)

print('v1_pow2', '\n', v1_pow2)
print('v1_pow3', '\n', v1_pow3)
print('v1_pow4', '\n', v1_pow4)

v1_pow2 
 [[  1.   4.   9.  16.  25.]
 [ 36.  49.  64.  81. 100.]
 [121. 144. 169. 196. 225.]
 [256. 289. 324. 361. 400.]
 [441. 484. 529. 576. 625.]]
v1_pow3 
 [[1.0000e+00 8.0000e+00 2.7000e+01 6.4000e+01 1.2500e+02]
 [2.1600e+02 3.4300e+02 5.1200e+02 7.2900e+02 1.0000e+03]
 [1.3310e+03 1.7280e+03 2.1970e+03 2.7440e+03 3.3750e+03]
 [4.0960e+03 4.9130e+03 5.8320e+03 6.8590e+03 8.0000e+03]
 [9.2610e+03 1.0648e+04 1.2167e+04 1.3824e+04 1.5625e+04]]
v1_pow4 
 [[1.00000e+00 1.60000e+01 8.10000e+01 2.56000e+02 6.25000e+02]
 [1.29600e+03 2.40100e+03 4.09600e+03 6.56100e+03 1.00000e+04]
 [1.46410e+04 2.07360e+04 2.85610e+04 3.84160e+04 5.06250e+04]
 [6.55360e+04 8.35210e+04 1.04976e+05 1.30321e+05 1.60000e+05]
 [1.94481e+05 2.34256e+05 2.79841e+05 3.31776e+05 3.90625e+05]]


In [5]:
image1 = np.zeros((300,300), np.uint8)
image2 = image1.copy()

h, w = image1.shape[:2]
cx, cy = w//2, h//2
cv2.circle(image1, (cx,cy), 100,255,-1)
cv2.rectangle(image2, (0,0, cx,h), 255,-1)

image3 = cv2.bitwise_or(image1, image2)
image4 = cv2.bitwise_and(image1, image2)
image5 = cv2.bitwise_xor(image1, image2)
image6 = cv2.bitwise_not(image1)

cv2.imshow("image1", image1)
cv2.imshow("image2", image2)
cv2.imshow("bitwise_or", image3)
cv2.imshow("bitwise_and", image4)
cv2.imshow("bitwise_xor", image5)
cv2.imshow("bitwise_not", image6)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [17]:
image = cv2.imread("images/bit_test_star.jpg", cv2.IMREAD_COLOR)
logo = cv2.imread("images/logo.jpg", cv2.IMREAD_COLOR)
if image is None or logo is None:
    raise Exception("영상 파일 읽기 오류")

image2 = image.copy()

masks = cv2.threshold(logo, 220, 255, cv2.THRESH_BINARY)[1]
masks = cv2.split(masks)

fg_pass_mask = cv2.bitwise_or(masks[0], masks[1])
fg_pass_mask = cv2.bitwise_or(masks[2], fg_pass_mask)
bg_pass_mask = cv2.bitwise_not(fg_pass_mask)

(H,W), (h,w) = image.shape[:2], logo.shape[:2]
x,y = (W-w)//2, (H-h)//2
roi = image[y:y+h, x:x+w]
roi2 = image2[y:y+h, x:x+w].copy()

foreground = cv2.bitwise_and(logo, logo, mask=fg_pass_mask)
background = cv2.bitwise_and(roi, roi, mask=bg_pass_mask)

bfa = cv2.add(background, foreground)
image2[y:y+h, x:x+w] = bfa

cv2.imshow("image", image)
cv2.imshow("logo", logo)
cv2.imshow("roi", roi)
cv2.imshow("roi2", roi2)
cv2.imshow("fg_pass_mask", fg_pass_mask)
cv2.imshow("bg_pass_mask",bg_pass_mask)
cv2.imshow("background", background)
cv2.imshow("foreground", foreground)
cv2.imshow("bfa", bfa)
cv2.imshow("image2", image2)
cv2.waitKey()
cv2.destroyAllWindows()

In [15]:
img = cv2.imread('images/girl.jpg')
if img is None:
    raise Exception("영상 읽기 오류")

mask = np.zeros_like(img)
cv2.circle(mask, (150, 140), 100, (255,255,255), -1)

masked = cv2.bitwise_and(img, mask)

cv2.imshow('original', img)
cv2.imshow('mask', mask)
cv2.imshow('maksed', masked)
cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
fore = cv2.imread('images/airplane.bmp', cv2.IMREAD_COLOR)
mask = cv2.imread('images/mask_plane.bmp', cv2.IMREAD_GRAYSCALE)
back = cv2.imread('images/field.bmp', cv2.IMREAD_COLOR)

if fore is None or mask is None or back is None:
    raise Exception("영상 파일 오류")

cv2.imshow('fore', fore)
cv2.imshow('mask', mask)
cv2.imshow('back', back)

final = cv2.copyTo(fore, mask, back)
cv2.imshow('final', final)

cv2.waitKey()
cv2.destroyAllWindows()