In [1]:
import numpy as np
import cv2

In [2]:
image = np.zeros((300,400), np.uint8) #300 x 400 행렬생성, 8비트 부호없는 정수형
image.fill(200) # 밝은회색으로 바탕 채우기

cv2.imshow('Window title', image)#imshow(윈도우이름, 행렬영상), 영상보기
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [3]:
array1 = np.array([0,0,0,0])
print('array1', '\n', array1)
print(type(array1))
print(array1.dtype)
print(array1.shape)
print(array1.ndim)
print()

array1 = np.array([1,1,1,1])
print('array1', '\n', array1)
print(type(array1))
print(array1.dtype)
print(array1.shape)
print(array1.ndim)
print()

array1 
 [0 0 0 0]
<class 'numpy.ndarray'>
int32
(4,)
1

array1 
 [1 1 1 1]
<class 'numpy.ndarray'>
int32
(4,)
1



In [4]:
zeros1 = np.zeros((4))
print('zeros1', '\n', zeros1)
print(type(zeros1))
print(zeros1.dtype)
print(zeros1.shape)
print(zeros1.ndim)
print()

ones1 = np.ones((4))
print('ones1', '\n', ones1)
print(type(ones1))
print(ones1.dtype)
print(ones1.shape)
print(ones1.ndim)
print()


zeros1 
 [0. 0. 0. 0.]
<class 'numpy.ndarray'>
float64
(4,)
1

ones1 
 [1. 1. 1. 1.]
<class 'numpy.ndarray'>
float64
(4,)
1



In [5]:
array2 = np.array([[0,0,0,0],
                  [1,2,3,4],
                 [1,2,3,4]])
print('array2', '\n', array2)
print(type(array2))
print(array2.dtype)
print(array2.shape)
print(array2.ndim)
print()


array2 
 [[0 0 0 0]
 [1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
int32
(3, 4)
2



In [6]:
zeros2 = np.zeros((3,4))
print('zeros2', '\n', zeros2)
print(type(zeros2))
print(zeros2.dtype)
print(zeros2.shape)
print(zeros2.ndim)
print()

ones2 = np.ones((3,4))
print('ones1', '\n', ones2)
print(type(ones2))
print(ones2.dtype)
print(ones2.shape)
print(ones2.ndim)
print()


zeros2 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(3, 4)
2

ones1 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>
float64
(3, 4)
2



In [7]:
image = np.zeros((200,400), np.uint8)
for i in range(0, 200, 10):
    image[i:i+10] = i
title1, title2 = 'Position1', 'Position2'
cv2.namedWindow(title1, cv2.WINDOW_AUTOSIZE)
cv2.namedWindow(title2)
cv2.moveWindow(title1, 150,150)
cv2.moveWindow(title2, 400,50)
cv2.imshow(title1, image)
cv2.imshow(title2, image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import numpy as np
import cv2
image = np.zeros((200,300), np.uint8)
image.fill(255)
title1, title2 = 'AUTOSIZE', 'NORMAL'
cv2.namedWindow(title1, cv2.WINDOW_AUTOSIZE)
cv2.namedWindow(title2, cv2.WINDOW_NORMAL)
cv2.resizeWindow(title1, 400, 300)
cv2.resizeWindow(title2, 400, 300)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
def onMouse(event, x,y,flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print("마우스 왼쪽 버튼 누르기")
    elif event == cv2.EVENT_RBUTTONDOWN:
        print("마우스 오른쪽 버튼 누르기")
    elif event == cv2.EVENT_RBUTTONUP:
        print("마우스 오른쪽 버튼 떼기")
    elif event == cv2.EVENT_LBUTTONDBLCLK:
        print("마우스 왼쪽 버튼 더블클릭")
image = np.full((200, 300), 255, np.uint8)
    
title1, title2 = "Mouse Event1", "Mouse Event2"
cv2.imshow(title1, image)
cv2.imshow(title2, image)

cv2.setMouseCallback(title1, onMouse)
cv2.setMouseCallback(title2, onMouse)
cv2.waitKey(0)
cv2.destroyAllWindows()

마우스 왼쪽 버튼 누르기
마우스 왼쪽 버튼 더블클릭
마우스 왼쪽 버튼 누르기
마우스 왼쪽 버튼 더블클릭
마우스 오른쪽 버튼 누르기
마우스 왼쪽 버튼 누르기
마우스 오른쪽 버튼 떼기
마우스 오른쪽 버튼 누르기
마우스 왼쪽 버튼 누르기
마우스 오른쪽 버튼 떼기
마우스 왼쪽 버튼 누르기
마우스 오른쪽 버튼 누르기
마우스 왼쪽 버튼 누르기
마우스 오른쪽 버튼 떼기
마우스 오른쪽 버튼 누르기
마우스 왼쪽 버튼 누르기
마우스 오른쪽 버튼 떼기
마우스 오른쪽 버튼 누르기
마우스 왼쪽 버튼 누르기
마우스 오른쪽 버튼 떼기
마우스 오른쪽 버튼 누르기
마우스 왼쪽 버튼 누르기
마우스 오른쪽 버튼 떼기
마우스 왼쪽 버튼 누르기
마우스 왼쪽 버튼 더블클릭
마우스 왼쪽 버튼 누르기
마우스 왼쪽 버튼 누르기
마우스 왼쪽 버튼 더블클릭
마우스 오른쪽 버튼 누르기
마우스 오른쪽 버튼 떼기
마우스 왼쪽 버튼 누르기
마우스 오른쪽 버튼 누르기
마우스 왼쪽 버튼 누르기
마우스 오른쪽 버튼 떼기
마우스 오른쪽 버튼 누르기
마우스 왼쪽 버튼 누르기
마우스 오른쪽 버튼 떼기


In [15]:
def onMouse(event, x,y,flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print("마우스 왼쪽 버튼 누르기 -> x:{}, y:{}".format(x,y))
    elif event == cv2.EVENT_RBUTTONDOWN:
        print("마우스 오른쪽 버튼 누르기 -> x:{}, y:{}".format(x,y))
    elif event == cv2.EVENT_RBUTTONUP:
        print("마우스 오른쪽 버튼 떼기 -> x:{}, y:{}".format(x,y))
    elif event == cv2.EVENT_LBUTTONDBLCLK:
        print("마우스 왼쪽 버튼 더블클릭 -> x:{}, y:{}".format(x,y))
image = np.full((200, 300), 0, np.uint8)
    
title1, title2 = "Mouse Event1", "Mouse Event2"
cv2.imshow(title1, image)
cv2.imshow(title2, image)

cv2.setMouseCallback(title1, onMouse)
cv2.setMouseCallback(title2, onMouse)
cv2.waitKey(0)
cv2.destroyAllWindows()

마우스 왼쪽 버튼 누르기 -> x:160, y:86
마우스 왼쪽 버튼 누르기 -> x:73, y:100
마우스 왼쪽 버튼 누르기 -> x:68, y:69
마우스 왼쪽 버튼 누르기 -> x:157, y:110
마우스 왼쪽 버튼 누르기 -> x:64, y:99
마우스 왼쪽 버튼 누르기 -> x:102, y:86
마우스 왼쪽 버튼 누르기 -> x:157, y:118
마우스 왼쪽 버튼 누르기 -> x:170, y:118


In [23]:
def on_level_change1(pos):
    value = pos * 1
    if value >= 255:
        value = 255
    img[:100] = value
    cv2.imshow('image', img)

def on_level_change2(pos):
    value = pos * 1
    if value >= 255:
        value = 255
    img[100:200] = value
    cv2.imshow('image', img)
    
def on_level_change3(pos):
    value = pos * 1
    if value >= 255:
        value = 255
    img[200:] = value
    cv2.imshow('image', img)
img = np.zeros((350,700), np.uint8)

cv2.namedWindow('image', cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 500, 500)
cv2.createTrackbar('level1', 'image', 0, 255, on_level_change1)
cv2.createTrackbar('level2', 'image', 0, 255, on_level_change2)
cv2.createTrackbar('level3', 'image', 0, 255, on_level_change3)

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
import numpy as np
import cv2
blue, green, red = ((255,0,0), (0,255,0), (0,0,255))
image = np.zeros((400,600), np.uint8)
image[:] = 255

pt1, pt2 = (50,50), (150,150)
pt3, pt4 = (400, 150), (500, 50)
roi = 50, 200, 200, 100
cv2.line(image, pt1, pt2, red)
cv2.line(image, pt3, pt4, green, 3, cv2.LINE_AA)

cv2.rectangle(image, pt1, pt2, blue, 3, cv2.LINE_4)
cv2.rectangle(image, roi, red, 3, cv2.LINE_8)
cv2.rectangle(image, (400,200,100,100), green, cv2.FILLED)

cv2.imshow('Line & Rectangle', image)
cv2.waitKey(0)
cv2.destroyAllWindows()



In [16]:
blue, green, red , mycolor= ((255,0,0), (0,255,0), (0,0,255), (50,100,40))
image = np.zeros((400,600, 3), np.uint8) # RGB 3차원 배열로 생성
image[:] = 255

pt1, pt2 = (50,50), (150,150)
pt3, pt4 = (400, 150), (500, 50)
roi = 50, 200, 200, 100
cv2.line(image, pt1, pt2, red)
cv2.line(image, pt3, pt4, green, 3, cv2.LINE_AA)

# cv2.rectangle(image, pt1, pt2, blue, 3, cv2.LINE_4)
cv2.rectangle(image, roi, red, 3, cv2.LINE_8)
cv2.rectangle(image, (400,200,100,100), green, cv2.FILLED)
cv2.rectangle(image, pt1, pt2, mycolor, 3, cv2.LINE_4)

cv2.imshow('Line & Rectangle', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
olive, violet, brown = (128, 128, 0), (221, 160, 221), (42, 42, 165)
pt1, pt2 = (50, 200), (50, 260)
image = np.zeros ((300, 500, 3), np.uint8)
image.fill(255)
cv2.putText(image, "SIMPLEX", (100, 100) ,cv2.FONT_HERSHEY_SIMPLEX, 3, brown)
cv2.putText(image, "DUPLEX" , (100, 100),cv2.FONT_HERSHEY_DUPLEX , 3, olive)
cv2.putText(image, "TRIPLEX", pt1, cv2.FONT_HERSHEY_TRIPLEX, 2, violet)
fontFace = cv2.FONT_HERSHEY_PLAIN + cv2.FONT_ITALIC
cv2.putText(image, "ITALIC" , pt2, fontFace , 4, violet)
cv2.imshow("Put Text"  , image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
img = np.zeros ((500, 700, 3), np.uint8)
img.fill (255)
cv2.circle( img , (100, 250), 40, (0,0,255), -1)
cv2.circle( img , (150, 250), 60, (0,127,255), -1)
cv2.circle( img , (210, 250), 80, (0,255,255), -1)
cv2.circle( img , (270, 250), 100, (0,255,0), -1)
cv2.circle( img , (330, 250), 120, (255,0,0), -1)
cv2.circle( img , (390, 250), 140, (128,0,0), -1)
cv2.circle( img , (450, 250), 160, (255,0,139), -1)
font = cv2.FONT_HERSHEY_SCRIPT_COMPLEX
cv2.putText( img , "r", (100, 50), font, 1, (0,0,255))
cv2.putText( img , "o", (150, 50), font, 1, (0,127,255))
cv2.putText( img , "y", (210, 50), font, 1, (0,255,255))
cv2.putText( img , "g", (270, 50), font, 1, (0,255,255))
cv2.putText( img , "b", (330, 50), font, 1, (255,0,0))
cv2.putText( img , "n", (390, 50), font, 1, (128,0,0))
cv2.putText( img , "p", (450, 50), font, 1, (255,0,139))
cv2.imshow('circle', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [36]:
orange, blue, white = (0,165,255), (255,0,0), (255,255,255)
image = np.full((300,700, 3), white, np.uint8)
pt1, pt2 = (180,150), (550, 150)
size = (120,60)

cv2.circle(image, pt1, 1,0,2)
cv2.circle(image, pt2, 1,0,2)

cv2.ellipse(image,pt1,size, 0, 0, 360, blue, 1)
cv2.ellipse(image,pt1,size, 0, 30, 270, orange, 4)
cv2.ellipse(image,pt2,size, 90, 0, 360, blue, 1)
cv2.ellipse(image,pt2,size, 90, -45, 90, orange, 4)

cv2.imshow("Draw Eclipse & Arc", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [70]:
import numpy as np
import cv2

red = (0,0,255)
blue = (255, 0, 0)
black = (0,0,0)
center = (150,100)
left_center = (129,88)
right_center = (171, 112)

image = np.zeros((200,300,3), np.uint8)
image[:] = 255

cv2.ellipse(image, center, (50, 50), 210, 0, 180, red, -1)
cv2.ellipse(image, center, (50, 50), 30, 0, 180, blue, -1)
cv2.ellipse(image, left_center, (25, 25), 0, 0, 360, red, -1)
cv2.ellipse(image, right_center, (25, 25), 0, 0, 360, blue, -1)
cv2.line(image, (15,40), (40, 10), black, cv2.LINE_4)
cv2.line(image, (25,50), (50, 20), black, cv2.LINE_4)
cv2.line(image, (35,60), (60, 30), black, cv2.LINE_4)

cv2.line(image, (200,150),(230, 110), black, cv2.LINE_4)
cv2.line(image, (25,50), (50, 20), black, cv2.LINE_4)
cv2.line(image, (35,60), (60, 30), black, cv2.LINE_4)


cv2.namedWindow('korea', cv2.WINDOW_NORMAL)
cv2.imshow('korea', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [69]:
def on_level_change(pos):
    value = pos * 1
    if value >= 255:
        value = 255
    r = cv2.getTrackbarPos('R', 'image')
    g = cv2.getTrackbarPos('G', 'image')
    b = cv2.getTrackbarPos('B', 'image')
    img[:] = [b,g,r]
    cv2.imshow('image', img)
    
img = np.zeros((350, 500,3), np.uint8)
cv2.namedWindow('image', cv2.WINDOW_NORMAL)
cv2.createTrackbar('R', 'image', 0, 255, on_level_change)
cv2.createTrackbar('G', 'image', 0, 255, on_level_change)
cv2.createTrackbar('B', 'image', 0, 255, on_level_change)
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()